INSERT INTO Produit (nom, description, prix, stock) VALUES
('Ordinateur Portable HP', 'Ordinateur portable HP avec processeur Intel Core i5, 8 Go de RAM et 256 Go de SSD.', 749.99, 50),
('Smartphone Samsung Galaxy S21', 'Smartphone Samsung Galaxy S21 avec écran AMOLED 6.2 pouces, 128 Go de stockage.', 999.99, 30),
('Imprimante Canon PIXMA', 'Imprimante tout-en-un Canon PIXMA avec fonctions de copie, numérisation et impression.', 149.99, 20),
('Téléviseur LG OLED 55 pouces', 'Téléviseur LG OLED 4K Ultra HD avec support HDR10 et Dolby Vision.', 1299.99, 15),
('Réfrigérateur Samsung', 'Réfrigérateur Samsung avec technologie No Frost, capacité de 340 litres et classe énergétique A++.', 699.99, 10),
('Lave-linge Bosch', 'Lave-linge Bosch avec capacité de 8 kg, vitesse d\'essorage de 1400 tr/min et classe énergétique A+++.', 499.99, 25),
('Micro-ondes Whirlpool', 'Micro-ondes Whirlpool avec 30 litres de capacité, fonction grill et 10 programmes automatiques.', 199.99, 40),
('Casque Audio Sony WH-1000XM4', 'Casque audio sans fil Sony avec réduction de bruit active et autonomie de 30 heures.', 349.99, 35),
('Tablette Apple iPad Air', 'Tablette Apple iPad Air avec écran Retina de 10.9 pouces, 64 Go de stockage et puce A14 Bionic.', 649.99, 25),
('Climatiseur Portable Delonghi', 'Climatiseur portable Delonghi avec puissance de refroidissement de 12000 BTU et télécommande.', 549.99, 10),
('Disque Dur Externe Seagate', 'Disque dur externe Seagate de 2 To avec connectivité USB 3.0.', 89.99, 50),
('Machine à Café Nespresso', 'Machine à café Nespresso avec système de capsules et réservoir d\'eau de 1 litre.', 129.99, 20),
('Aspirateur Dyson V11', 'Aspirateur sans fil Dyson V11 avec autonomie de 60 minutes et divers accessoires de nettoyage.', 599.99, 15),
('Écran PC Dell UltraSharp', 'Écran PC Dell UltraSharp de 27 pouces avec résolution 4K et technologie IPS.', 449.99, 20),
('Enceinte Bluetooth JBL', 'Enceinte Bluetooth JBL avec 20 heures d\'autonomie et résistance à l\'eau (IPX7).', 99.99, 30),
('Cuisinière Induction Electrolux', 'Cuisinière à induction Electrolux avec 4 zones de cuisson et four multifonctions de 72 litres.', 799.99, 10),
('Caméra de Sécurité Arlo', 'Caméra de sécurité Arlo avec résolution 1080p, vision nocturne et audio bidirectionnel.', 199.99, 25),
('Routeur Wi-Fi Netgear', 'Routeur Wi-Fi Netgear avec technologie tri-bande et support des dernières normes Wi-Fi 6.', 299.99, 30),
('Montre Connectée Fitbit', 'Montre connectée Fitbit avec suivi de la condition physique, GPS intégré et autonomie de 7 jours.', 149.99, 35),
('Four Micro-ondes Samsung', 'Four micro-ondes Samsung avec technologie de cuisson par convection et capacité de 28 litres.', 229.99, 20),
('Carte Mémoire SanDisk', 'Carte mémoire SanDisk microSDXC de 128 Go avec adaptateur SD.', 29.99, 50),
('Tondeuse à Cheveux Philips', 'Tondeuse à cheveux Philips avec 12 réglages de longueur et autonomie de 90 minutes.', 59.99, 25),
('Cafetière Filtre Moulinex', 'Cafetière filtre Moulinex avec capacité de 1.25 litres et fonction maintien au chaud.', 39.99, 40),
('Sèche-cheveux Remington', 'Sèche-cheveux Remington avec moteur AC de 2200 W et 3 réglages de température.', 49.99, 30),
('Chargeur Sans Fil Anker', 'Chargeur sans fil Anker compatible avec la charge rapide Qi et sortie 10W.', 24.99, 50);
